# Project-specific AEM configuration

# Inherit default AEM functionality from "AEM Definitions", see http://devops.wcm.io/conga/definitions/aem/
inherits:
- role: aem-cms

variants:
- variant: aem-author
- variant: aem-publish

templateDir: ${projectName}-aem-cms

files:

#if ( $optionAemServicePack == 'y' )
#if ( $optionAemVersion == '6.3' )
# AEM Service Pack
- url: mvn:adobe.binary.aem.63.servicepack/AEM-6.3.3.0/6.3.3/zip
  dir: packages
  modelOptions:
    delayAfterInstallSec: 30
# Minimum CFP required by AEM core components. There was a "first deployment" problem with CFP7, so use CFP4.
- url: mvn:adobe.binary.aem.63.cumulativefixpack/AEM-CFP-6.3.3.4/4.0/zip
  dir: packages
  modelOptions:
    delayAfterInstallSec: 30
#elseif ( $optionAemVersion == '6.4' )
# AEM Service Pack
- url: mvn:adobe.binary.aem.64.servicepack/AEM-6.4.8.0/6.4.8/zip
  dir: packages
  modelOptions:
    delayAfterInstallSec: 30
#elseif ( $optionAemVersion == '6.5' )
# AEM Service Pack
- url: mvn:adobe.binary.aem.65.servicepack/aem-service-pkg/6.5.5/zip
  dir: packages
  modelOptions:
    delayAfterInstallSec: 30
#end
#end

#if ( $optionAemVersion != "cloud" )
# AEM Core WCM components
- url: mvn:com.adobe.cq/core.wcm.components.all//zip
  dir: packages

#end
#if( $optionAcsCommons == "y" )
# ACS AEM Commons
- url: mvn:com.adobe.acs/acs-aem-commons-ui.apps//zip/min
  dir: packages
  postProcessorOptions:
    contentPackage.packageType: application
- url: mvn:com.adobe.acs/acs-aem-commons-ui.content//zip/min
  dir: packages
  postProcessorOptions:
    contentPackage.packageType: content

#end
# AEM OSGi System Configuration
- file: ${projectName}-aem-cms-config.provisioning
  dir: packages
  template: ${projectName}-aem-cms-config.provisioning.hbs
  postProcessors:
  - aem-contentpackage-osgiconfig
  postProcessorOptions:
    contentPackage:
      name: ${projectName}-aem-cms-config
      rootPath: /apps/${projectName}/config
      filters:
      - filter: /apps/${projectName}
        rules:
        - rule: include
          pattern: /apps/${projectName}/config(\..*)?(/.*)?
        - rule: exclude
          pattern: /apps/${projectName}/config/rewriter(/.*)?

#if ( $optionWcmioHandler == "y" )
# Include URL handler in Sling Rewriter configuration
- file: ${projectName}-aem-cms-rewriter-config.json
  dir: packages
  template: ${projectName}-aem-cms-rewriter-config.json.hbs
  validatorOptions:
    contentPackage.validatorsSettings:
      jackrabbit-filter:
        options:
          validRoots: /apps/${projectName}/config
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: ${projectName}-aem-cms-rewriter-config
      packageType: application
      acHandling: merge
      rootPath: /apps/${projectName}/config/rewriter

#end
# Application package
- url: mvn:${groupId}/${rootArtifactId}.complete//zip
  dir: packages

#if ( $optionEditableTemplates == "y" )
# Application conf content package
- url: mvn:${groupId}/${rootArtifactId}.conf-content//zip
  dir: packages
  condition: ${app.confContent}

#end
# Application sample content package
- url: mvn:${groupId}/${rootArtifactId}.sample-content//zip
  dir: packages
  condition: ${app.sampleContent}


# Defines configuration parameters and default values
config:
  contentPackage:
    group: ${packageGroupName}
    #[[version: ${version}]]#

  app:
#if ( $optionContextAwareConfig == "y" || $optionEditableTemplates == "y" )
    confContent: true
#end
    sampleContent: false

#if ( $optionAemVersion == "cloud" )
  # Replication configuration not required for AEM cloud service
  replication:
    author.generatePackage: false
    publish.generatePackage: false

#end
  # Log levels
  log:
    projectSpecificLogLevel: warn
