# Project-specific AEM configuration

# Inherit default AEM functionality from "AEM Definitions", see http://devops.wcm.io/conga/definitions/aem/
inherits:
- role: aem-cms

variants:
- variant: aem-author
- variant: aem-publish

templateDir: ${projectName}-aem-cms

files:

#if ( $optionAemServicePack == 'y' )
#if ( $optionAemVersion == '6.3' )
# AEM Service Pack
- url: mvn:adobe.binary.aem.63.servicepack/AEM-6.3.3.0/6.3.3/zip
  dir: packages
  modelOptions:
    delayAfterInstallSec: 30
#elseif ( $optionAemVersion == '6.4' )
# AEM Service Pack
- url: mvn:adobe.binary.aem.64.servicepack/AEM-6.4.4.0/6.4.4/zip
  dir: packages
  modelOptions:
    delayAfterInstallSec: 30
#end
#end

# AEM Core WCM components
- url: mvn:com.adobe.cq/core.wcm.components.all//zip
  dir: packages

#if( $optionAcsCommons == "y" )
# ACS AEM Commons
- url: mvn:com.adobe.acs/acs-aem-commons-content//zip/min
  dir: packages

#end
# AEM OSGi System Configuration
- file: ${projectName}-aem-cms-config.provisioning
  dir: packages
  template: ${projectName}-aem-cms-config.provisioning.hbs
  postProcessors:
  - aem-contentpackage-osgiconfig
  postProcessorOptions:
    contentPackage:
      name: ${projectName}-aem-cms-config
      rootPath: /apps/${projectName}/config
      filters:
      - filter: /apps/${projectName}
        rules:
        - rule: include
          pattern: /apps/${projectName}/config(\..*)?
        - rule: exclude
          pattern: /apps/${projectName}/config/rewriter

#if ( $optionWcmioHandler == "y" )
# Include URL handler in Sling Rewriter configuration
- file: ${projectName}-aem-cms-rewriter-config.json
  dir: packages
  template: ${projectName}-aem-cms-rewriter-config.json.hbs
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: ${projectName}-aem-cms-rewriter-config
      acHandling: merge
      rootPath: /apps/${projectName}/config/rewriter

# AEM Systems users with ACLs (Author)
- file: ${projectName}-aem-cms-author-systemusers.json
  dir: packages
  template: ${projectName}-aem-cms-author-systemusers.json.hbs
  variants:
  - aem-author
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: ${projectName}-aem-cms-author-systemusers
      acHandling: merge
      rootPath: /
      filters:
      - filter: /content/dam/rep:policy
      - filter: /home/users/system/${projectName}/${projectName}DamSystemUser

#end
# Application package
- url: mvn:${groupId}/${rootArtifactId}.complete//zip
  dir: packages

#if ( $optionEditableTemplates == "y" )
# Application conf content package
- url: mvn:${groupId}/${rootArtifactId}.conf-content//zip
  dir: packages
  condition: ${app.confContent}

#end
# Application sample content package
- url: mvn:${groupId}/${rootArtifactId}.sample-content//zip
  dir: packages
  condition: ${app.sampleContent}


# Defines configuration parameters and default values
config:
  contentPackage:
    group: ${packageGroupName}
    #[[version: ${version}]]#

  app:
#if ( $optionContextAwareConfig == "y" || $optionEditableTemplates == "y" )
    confContent: true
#end
    sampleContent: false

  # Log levels
  log:
    projectSpecificLogLevel: warn
